inicio/urls.py
from django.urls import path
from inicio import views # IMPORTO DESDE views.py

app_name = "inicio" #por si llegamos a crear dos urls con el mismo nombre pero con diferente app usamos esta funcion para diferenciarlas

urlpatterns = [
    path("",views.inicio, name= "inicio"),
    path("prueba", views.prueba, name= "prueba"), 
    path("segunda-vista/",views.segunda_vista, name="segunda_vista"),
    path("fecha-actual/",views.fecha_actual, name="fecha_actual"),
    path("saludo/",views.saludo, name="saludo"),
    path("bienvenida/<str:nombre>/<str:apellido>/",views.bienvenida, name="bienvenida"),
    
    #path("crear-perro/<str:nombre>/<int:edad>/",views.crear_perro, name="crear_perro"),
    #VISTAS COMUNES
    #path("perro/",views.listar_perro, name="listar_perro"),
    #path("perro/crear/",views.crear_perro, name="crear_perro"),
    #path("perro/modificar/<int:perro_id>/",views.modificar_perro, name="modificar_perro"),
    #path("perro/eliminar/<int:perro_id>/",views.eliminar_perro, name="eliminar_perro"),


    #CBV
    path("perro/crear/",views.CrearPerro.as_view(), name="crear_perro"),
    path("perros/",views.ListarPerros.as_view(), name="listar_perros"),
    path("perro/modificar/<int:pk>/",views.ModificarPerro.as_view(), name="modificar_perro"),
    path("perro/eliminar/<int:pk>/",views.EliminarPerro.as_view(), name="eliminar_perro"),
    path("perro/<int:pk>/",views.MostrarPerro.as_view(), name="mostrar_perro"),


]

mi_primer_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("inicio.urls")),
    path("usuario/", include("usuario.urls")),
    path('admin/', admin.site.urls),   
]

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView
app_name = "usuario"

urlpatterns = [
    path("login/",views.login,name="login"),
    path("logout/",LogoutView.as_view(template_name="usuario/logout.html"),name="logout"),
    path("registro/",views.registrarse, name="registrarse")

    
]

inicio/models.py
from django.db import models

# Create your models here.
class Perro(models.Model): #tratar de poner como nombre algo en singular
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    descripcion = models.TextField(null=True)

    def __str__(self):
        return f"perro: {self.nombre} - edad:{self.edad}"
    

usuario/models.py
from django.db import models

# Create your models here.

inicio/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from inicio.models import Perro
from inicio.form import CrearPerroFormulario, BuscarPerroFormulario, ModificarPerroFormulario
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


def prueba(request):
    segundos = datetime.now().second
    diccionario = {
    "mensaje": "alilililili",
    "segundos": segundos,
    "segundo_par" : segundos%2 == 0,
    "segundo_redondo": segundos%10 == 0,
    "listado_de_numeros" : list(range(25))
    }
    return render(request,"inicio/prueba.html",diccionario)


def segunda_vista(request):
    return HttpResponse("<h1>soy la segunda vista</h1>")

def inicio(request):
    return render(request,"inicio/inicio.html")

def fecha_actual(request):
    fecha = datetime.now()
    return HttpResponse(f"la fecha es: {fecha}")

def saludo(request):
    return HttpResponse("hola")

def bienvenida(request, nombre, apellido):
    return HttpResponse(f"bienvenido {nombre} {apellido}!!!") 
"""v1 crear perro
def crear_perro(request, nombre, edad):
    perro = Perro(nombre=nombre,edad=edad)
    perro.save()
    diccionario = {
        "perro":perro,
    }
    return render(request,"inicio/crear_perro.html",diccionario)
"""
"""
#v2 crear perro
def crear_perro(request):

    if request.method == "POST":
        formulario = CrearPerroFormulario(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            perro = Perro(nombre=info["nombre"],edad=info["edad"])
            perro.save()
            return redirect("inicio:listar_perro")
        else:
            return render(request,"inicio/crear_perro.html",{"formulario": formulario})

    formulario = CrearPerroFormulario()
    return render(request,"inicio/crear_perro.html",{"formulario": formulario})



def listar_perro(request):
    request.GET
    formulario = BuscarPerroFormulario(request.GET)
    if formulario.is_valid():
        nombre_a_buscar = formulario.cleaned_data["nombre"]
        listado_de_perro  = Perro.objects.filter(nombre__icontains = nombre_a_buscar)    

    formulario = BuscarPerroFormulario()
    return render(request,"inicio/listar_perro.html",{"formulario": formulario, "perros" : listado_de_perro})

def eliminar_perro(request, perro_id):
    perro = Perro.objects.get(id=perro_id)
    perro.delete()
    return redirect("inicio:listar_perro")

def modificar_perro(request, perro_id):
    perro_a_modificar = Perro.objects.get(id=perro_id)

    if request.method == "POST":
        formulario = ModificarPerroFormulario(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            perro_a_modificar.nombre = info["nombre"]
            perro_a_modificar.edad = info["edad"]
            perro_a_modificar.save()
            return redirect("inicio:listar_perro")
        else:
            return render(request,"inicio/modificar_perro.html",{"formulario":formulario})

    formulario = ModificarPerroFormulario(initial={"nombre":perro_a_modificar.nombre, "edad":perro_a_modificar.edad})
    return render(request,"inicio/modificar_perro.html",{"formulario":formulario})
   
""" 
class CrearPerro(CreateView):
    model = Perro
    template_name = "inicio/CBV/crear_perro_CBV.html"
    fields =["nombre","edad","descripcion"]
    success_url = reverse_lazy("inicio:listar_perros")

class ListarPerros(ListView):
    model = Perro
    template_name = "inicio/CBV/listar_perros_CBV.html"
    context_object_name = "perros"

class  ModificarPerro(UpdateView):
    model =  Perro
    template_name = "inicio/CBV/modificar_perro_CBV.html"
    fields =["nombre","edad","descripcion"]
    success_url = reverse_lazy("inicio:listar_perros")

class EliminarPerro(DeleteView):
    model = Perro
    template_name = "inicio/CBV/eliminar_perro_CBV.html"
    success_url = reverse_lazy("inicio:listar_perros")

class MostrarPerro(DetailView):
    model = Perro
    template_name ="inicio/CBV/mostrar_perro_CBV.html"

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login as django_login #como login la estamos usando para otra cosa desde la linea 7 le cambiamos el nombre a la que importamos


def login(request):

    if request.method == "POST":
        formulario = AuthenticationForm(request,data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data["username"]
            contrasenia = formulario.cleaned_data["password"]

            user = authenticate(username = usuario, password= contrasenia)

            django_login(request, user)
            return redirect("inicio:inicio")
        else:
            return render(request,"usuario/login.html",{"formulario": formulario})



    formulario = AuthenticationForm()
    return render(request,"usuario/login.html",{"formulario": formulario})


def registrarse(request):
    formulario = UserCreationForm
    return render(request, "usuario/registro.html", {"formulario": formulario})

inicio/templates/inicio/CBV/crear_perro_CBV.html
{% extends 'bases.html' %}
{% block title_head %}
<title>Crear perro</title>
{% endblock title_head %}

{% block h1_header %}
Crear perro
{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'inicio:crear_perro' %} method="POST" > {# POST es para guardar informacion o trabajarlas en alguna bd, en otro caso usamos GET#}
    {% csrf_token %} 
    <table>
    {{form}}
    </table>
    <button>Crear</button>
</form> 
{% endblock contenido %}

inicio/templates/inicio/CBV/eliminar_perro_CBV.html
{% extends 'bases.html' %}
{% block title_head %}
<title>Eliminar perro</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar perro
{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'inicio:eliminar_perro' perro.id %} method="POST" > {# POST es para guardar informacion o trabajarlas en alguna bd, en otro caso usamos GET#}
    {% csrf_token %} 
    <p> Confirma el borrado de {{perro}}? </p>
    <table>
    {{form}}
    </table>
    <button>Confirmar</button>
</form> 
{% endblock contenido %}

inicio/templates/inicio/CBV/listar_perros_CBV.html
{% extends 'bases.html' %}

{% block title_head %}
<title>Nuevos perro</title>
{% endblock title_head %}

{% block h1_header %}
lista de perro
{% endblock h1_header %}

{% block contenido %}
<button> 
    <a class="navbar-brand" href={% url 'inicio:crear_perro' %}>crear perro</a>

</button>
{% comment "" %}
<form action="" method = "get">
    {{formulario}}
<button>Buscar</button>
</form>
{% endcomment %}
{% if perros %}
{% for perro in perros %}
<li>
    {{perro}}

    <button> 
        <a class="navbar-brand" href= {% url 'inicio:eliminar_perro' perro.id %} >Eliminar</a>
    </button>
    <button> 
        <a class="navbar-brand" href= {% url 'inicio:modificar_perro' perro.id %} >Modificar</a>
    </button>
    <button> 
        <a class="navbar-brand" href= {% url 'inicio:mostrar_perro' perro.id %} >Detalle</a>
    </button>

</li>
{% endfor %}
{% else %}
<p>No se encontraron resultados</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_perro_CBV.html
{% extends 'bases.html' %}
{% block title_head %}
<title>modificar perro</title>
{% endblock title_head %}

{% block h1_header %}
modificar perro
{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'inicio:modificar_perro' perro.id %} method="POST" > {# POST es para guardar informacion o trabajarlas en alguna bd, en otro caso usamos GET#}
    {% csrf_token %} 
    <table>
    {{form}}
    </table>
    <button>modificar</button>
</form> 
{% endblock contenido %}
   

inicio/templates/inicio/CBV/mostrar_perro_CBV.html
{% extends 'bases.html' %}
{% block title_head %}
<title>perro</title>
{% endblock title_head %}

{% block h1_header %}
{{perro.nombre}}
{% endblock h1_header %}

{% block contenido %}
<li>Edad : {{perro.edad}} </li>
<li>Descripcion : {{perro.descripcion}} </li>
{% endblock contenido %}

inicio/templates/inicio/crear_perro.html
{% extends 'bases.html' %}
{% block title_head %}
<title>Crear perro</title>
{% endblock title_head %}

{% block h1_header %}
Crear perro
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST" > {# POST es para guardar informacion o trabajarlas en alguna bd, en otro caso usamos GET#}
    {% csrf_token %} 
    {{formulario}}
     
    <button>Crear</button>
</form> 
{% endblock contenido %}
   

inicio/templates/inicio/inicio.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= {% static  "css/styles.css" %} rel="stylesheet"  />    
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="#!">inicio</a>
                <a class="navbar-brand" href="#!">perros</a>
                <a class="btn btn-primary" href="#signup">iniciar</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Nuestra web intermedia de django</h1>

                            
                        </div>
                    </div>
                </div>
            </div>
        </header>
       
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

inicio/templates/inicio/listar_perro.html
{% extends 'bases.html' %}

{% block title_head %}
<title>Nuevos perro</title>
{% endblock title_head %}

{% block h1_header %}
{% comment "" %}se creo el perro {{perro.nombre}} que tiene {{perro.edad}} años{% endcomment %} 
lista de perro
{% endblock h1_header %}

{% block contenido %}
<button> 
    <a href={% url 'inicio:crear_perro' %}>crear perro</a>
</button>
<form action="" method = "get">
    {{formulario}}
<button>Buscar</button>
</form>
{% if perros %}
{% for perro in perros %}
<li>
    {{perro}}
    <a href= {% url 'inicio:eliminar_perro' perro.id %} >Eliminar</a>
    <a href= {% url 'inicio:modificar_perro' perro.id %} >Modificar</a>
</li>
{% endfor %}
{% else %}
<p>No se encontraron resultados</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/modificar_perro.html
{% extends 'bases.html' %}
{% block title_head %}
<title>modificar perro</title>
{% endblock title_head %}

{% block h1_header %}
modificar perro
{% endblock h1_header %}

{% block contenido %}
<form action="" method="POST" > {# POST es para guardar informacion o trabajarlas en alguna bd, en otro caso usamos GET#}
    {% csrf_token %} 
    <table>
    {{formulario}}
    </table>
    <button>modificar</button>
</form> 
{% endblock contenido %}
   

inicio/templates/inicio/perro.html
{% extends 'bases.html' %}

{% block title_head %}
<title>Nuevo perro</title>
{% endblock title_head %}

{% block h1_header %}
se creo el perro {{perro.nombre}} que tiene {{perro.edad}} años
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

inicio/templates/inicio/prueba.html
{% extends "bases.html" %}

{% block title_head %}
<title>Prueba</title>
{% endblock title_head %}

{% block h1_header %}
<h1>prueba</h1>
{% endblock h1_header %}

{% block contenido %}

    <h1>este es el primer template que cree</h1>
    <p>{{mensaje}}</p>
    
    {%  if segundo_redondo  %}  
    <p style="color: blue;">{{segundos}}</p>
    {% elif segundo_par %}
    <p style="color:yellow;">{{segundos}}</p>
    {% else %}
    <p style="color:black;">{{segundos}}</p>
    {%endif%}

    {% for numero in listado_de_numeros  %}
    <p>{{numero}}</p>
    {% endfor %}
  
{% endblock contenido %}

templates/bases.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template base</title>
        {% endblock title_head %}
         
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= {% static  "css/styles.css" %} rel="stylesheet"  />    
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>  <!-- linea 4 urls.py -->
                <a class="navbar-brand" href={% url 'inicio:prueba' %}>Prueba</a>  <!-- linea 4 urls.py -->
                <a class="navbar-brand" href={% url 'inicio:listar_perros' %}>Perro</a>
                {% if request.user.is_authenticated %}
                <a class="navbar-brand" href="#"> {{request.user.username}} </a>
                <a class="btn btn-secondary" href= {% url 'usuario:logout' %} >Logout</a>
                {% else %}
                <a class="btn btn-primary" href= {% url 'usuario:login' %} >Login</a>
                <a class="btn btn-primary" href= {% url 'usuario:registrarse' %} >Registrarse</a>

                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->

{% block header %}
<header class="masthead">
    <div class="container position-relative">
        <div class="row justify-content-center">
            <div class="col-xl-6">
                <div class="text-center text-white">
                    <!-- Page heading-->
                    {% block h1_header %}
                    <h1 class="mb-5">Nuestra web intermedia de django</h1>
                    {% endblock h1_header %}
                    
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}

{% block contenido %}
<p>Soy el template padre</p>
{% endblock contenido %}


                <!-- Footer-->
                <footer class="footer bg-light">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                                <ul class="list-inline mb-2">
                                    <li class="list-inline-item"><a href="#!">About</a></li>
                                    <li class="list-inline-item">⋅</li>
                                    <li class="list-inline-item"><a href="#!">Contact</a></li>
                                </ul>
                                <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                            </div>
                            <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                                <ul class="list-inline mb-0">
                                    <li class="list-inline-item me-4">
                                        <a href="#!"><i class="bi-facebook fs-3"></i></a>
                                    </li>
                                    <li class="list-inline-item me-4">
                                        <a href="#!"><i class="bi-twitter fs-3"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="#!"><i class="bi-instagram fs-3"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- Bootstrap core JS-->
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
                <!-- Core theme JS-->
                <script src="js/scripts.js"></script>
                <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
                <!-- * *                               SB Forms JS                               * *-->
                <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
                <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
                <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
            </body>
        </html>
        

templates/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>este es el primer template que cree</h1>
    <p>{{mensaje}}</p>
    
    {%  if segundo_redondo  %}  
    <p style="color: blue;">{{segundos}}</p>
    {% elif segundo_par %}
    <p style="color:yellow;">{{segundos}}</p>
    {% else %}
    <p style="color:black;">{{segundos}}</p>
    {%endif%}

    {% for numero in listado_de_numeros  %}
    <p>{{numero}}</p>
    {% endfor %}

</body>
</html>

usuario/templates/usuario/login.html
{% extends 'bases.html' %}
{% block title_head %}
<title>Login</title>
{% endblock title_head %}

{% block h1_header %}
Login{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'usuario:login' %} method="POST" >
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button>Login</button>
</form> 
{% endblock contenido %}

usuario/templates/usuario/logout.html
{% extends 'bases.html' %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
logout exitoso
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

usuario/templates/usuario/registro.html
{% extends 'bases.html' %}
{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
Registro{% endblock h1_header %}

{% block contenido %}
<form action= {% url 'usuario:registrarse' %} method="POST" >
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button>Registrar cuenta</button>
</form> 
{% endblock contenido %}